### ISSUE TITLE
Integrating with yii2-yee-post & yii2-yee-page

### ISSUE THREAD

**Issue by msoa** [yeesoft/yii2-yee-seo#3]
Is possible integrate the `yii2-yee-seo` with `yii2-yee-post & yii2-yee-page`? (like yoast in wordpress)

**Comment by yeesoft** [comment]
@msoa currently there no such feature. You need to create all seo records by yourself. Maybe this feature will be implemented within 0.2.x release.

**Comment by msoa** [comment]
Release is near?
